import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { FiShield, FiAlertTriangle } from 'react-icons/fi'
import { useAuth } from '../context/AuthContext'

export default function DisclaimerPage() {
  const [accepted, setAccepted] = useState(false)
  const [loading, setLoading] = useState(false)
  const { acceptDisclaimer, user } = useAuth()
  const navigate = useNavigate()

  const handleAccept = async () => {
    if (!accepted) return
    setLoading(true)
    try {
      await acceptDisclaimer()
      navigate('/app')
    } catch (e) {
      alert('Failed to accept')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background dark:bg-primary px-6 py-12">
      <motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} className="w-full max-w-3xl">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-accent/10 mb-4">
            <FiShield className="text-3xl text-accent" />
          </div>
          <h1 className="text-3xl font-bold mb-2">Important Legal Disclaimer</h1>
          <p className="text-gray-600 dark:text-gray-400">Please read carefully before using DigiLaw</p>
        </div>

        <div className="card">
          <div className="flex items-start gap-3 p-4 bg-amber-50 dark:bg-amber-900/20 rounded-xl mb-6 border border-amber-200 dark:border-amber-800">
            <FiAlertTriangle className="text-amber-600 text-xl shrink-0 mt-0.5" />
            <p className="text-sm text-amber-900 dark:text-amber-100">
              <strong>DigiLaw is for educational purposes only.</strong> It is not a substitute for professional legal advice.
            </p>
          </div>

          <div className="prose dark:prose-invert max-w-none space-y-4 text-sm leading-relaxed max-h-96 overflow-y-auto pr-2">
            <h3 className="font-semibold text-lg">1. Educational Purpose Only</h3>
            <p>DigiLaw provides general legal information and education about Indian laws. All content is for learning purposes only.</p>
            
            <h3 className="font-semibold text-lg">2. Not Legal Advice</h3>
            <p>We do NOT provide legal advice. We do NOT create an attorney-client relationship. For actual legal problems, consult a qualified lawyer.</p>
            
            <h3 className="font-semibold text-lg">3. No Warranty</h3>
            <p>Laws change frequently. While we strive for accuracy, we cannot guarantee information is current or complete. Always verify with official sources.</p>
            
            <h3 className="font-semibold text-lg">4. AI-Generated Content</h3>
            <p>Responses are generated by AI (Llama 3) using legal databases. AI can make mistakes. Do not rely solely on DigiLaw for important decisions.</p>
            
            <h3 className="font-semibold text-lg">5. Your Responsibility</h3>
            <p>You are responsible for how you use this information. DigiLaw and its creators are not liable for any actions taken based on the information provided.</p>
            
            <h3 className="font-semibold text-lg">6. Data Storage</h3>
            <p>Your chats and questions are stored to improve your experience. We do not share personal legal queries with third parties.</p>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200 dark:border-slate-700">
            <label className="flex items-start gap-3 cursor-pointer">
              <input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)}
                className="mt-1 w-5 h-5 rounded border-2 text-secondary focus:ring-secondary" />
              <span className="text-sm">
                I, <strong>{user?.full_name}</strong>, understand that DigiLaw is for educational purposes only, does not provide legal advice, and does not create an attorney-client relationship. I agree to use it responsibly.
              </span>
            </label>

            <button onClick={handleAccept} disabled={!accepted || loading}
              className="btn-primary w-full mt-6 disabled:opacity-50 disabled:cursor-not-allowed">
              {loading ? 'Processing...' : 'I Agree & Continue'}
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  )
}